# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/livew/Desktop/CX/chinx/chinx/chinx.srcs/sources_1/ip/rom32/rom32.xci
# IP: The module: 'rom32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/livew/Desktop/CX/chinx/chinx/chinx.srcs/sources_1/ip/rom32/rom32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/livew/Desktop/CX/chinx/chinx/chinx.srcs/sources_1/ip/rom32/rom32.xci
# IP: The module: 'rom32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/livew/Desktop/CX/chinx/chinx/chinx.srcs/sources_1/ip/rom32/rom32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
